package com.dy.framework.mybatis.mapper;

import com.dy.framework.mybatis.model.TUserPermission;
import com.dy.framework.mybatis.model.TUserPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int countByExample(TUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int deleteByExample(TUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int insert(TUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int insertSelective(TUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    List<TUserPermission> selectByExample(TUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") TUserPermission record, @Param("example") TUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_permission
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByExample(@Param("record") TUserPermission record, @Param("example") TUserPermissionExample example);
}