package com.dy.framework.mybatis.mapper;

import com.dy.framework.mybatis.model.TUserRole;
import com.dy.framework.mybatis.model.TUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int countByExample(TUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int deleteByExample(TUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int insert(TUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int insertSelective(TUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    List<TUserRole> selectByExample(TUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") TUserRole record, @Param("example") TUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByExample(@Param("record") TUserRole record, @Param("example") TUserRoleExample example);
}