package com.dy.framework.mybatis.mapper;

import com.dy.framework.mybatis.model.TUserProfile;
import com.dy.framework.mybatis.model.TUserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int countByExample(TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int deleteByExample(TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int insert(TUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int insertSelective(TUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    List<TUserProfile> selectByExampleWithBLOBs(TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    List<TUserProfile> selectByExample(TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    TUserProfile selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") TUserProfile record, @Param("example") TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TUserProfile record, @Param("example") TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByExample(@Param("record") TUserProfile record, @Param("example") TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByPrimaryKeySelective(TUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    int updateByPrimaryKey(TUserProfile record);
}