package com.dy.framework.mybatis.model;

import java.util.Date;

public class TPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.name
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.alias
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.description
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.create_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.update_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.version
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.id
     *
     * @return the value of t_permission.id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.id
     *
     * @param id the value for t_permission.id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.name
     *
     * @return the value of t_permission.name
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.name
     *
     * @param name the value for t_permission.name
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.alias
     *
     * @return the value of t_permission.alias
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.alias
     *
     * @param alias the value for t_permission.alias
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.description
     *
     * @return the value of t_permission.description
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.description
     *
     * @param description the value for t_permission.description
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.create_time
     *
     * @return the value of t_permission.create_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.create_time
     *
     * @param createTime the value for t_permission.create_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.update_time
     *
     * @return the value of t_permission.update_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.update_time
     *
     * @param updateTime the value for t_permission.update_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.version
     *
     * @return the value of t_permission.version
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.version
     *
     * @param version the value for t_permission.version
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}