package com.dy.framework.mybatis.model;

import java.util.Date;

public class TUserProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.user_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.nickname
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.email
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.email_checked
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Boolean emailChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.gender
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.description
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.location
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.create_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.update_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.version
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_profile.avatar
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private byte[] avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.user_id
     *
     * @return the value of t_user_profile.user_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.user_id
     *
     * @param userId the value for t_user_profile.user_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.nickname
     *
     * @return the value of t_user_profile.nickname
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.nickname
     *
     * @param nickname the value for t_user_profile.nickname
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.email
     *
     * @return the value of t_user_profile.email
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.email
     *
     * @param email the value for t_user_profile.email
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.email_checked
     *
     * @return the value of t_user_profile.email_checked
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Boolean getEmailChecked() {
        return emailChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.email_checked
     *
     * @param emailChecked the value for t_user_profile.email_checked
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setEmailChecked(Boolean emailChecked) {
        this.emailChecked = emailChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.gender
     *
     * @return the value of t_user_profile.gender
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.gender
     *
     * @param gender the value for t_user_profile.gender
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.description
     *
     * @return the value of t_user_profile.description
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.description
     *
     * @param description the value for t_user_profile.description
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.location
     *
     * @return the value of t_user_profile.location
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.location
     *
     * @param location the value for t_user_profile.location
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.create_time
     *
     * @return the value of t_user_profile.create_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.create_time
     *
     * @param createTime the value for t_user_profile.create_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.update_time
     *
     * @return the value of t_user_profile.update_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.update_time
     *
     * @param updateTime the value for t_user_profile.update_time
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.version
     *
     * @return the value of t_user_profile.version
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.version
     *
     * @param version the value for t_user_profile.version
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_profile.avatar
     *
     * @return the value of t_user_profile.avatar
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public byte[] getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_profile.avatar
     *
     * @param avatar the value for t_user_profile.avatar
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }
}