package com.dy.framework.mybatis.model;

public class TUserPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_permission.user_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_permission.permission_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    private Long permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_permission.user_id
     *
     * @return the value of t_user_permission.user_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_permission.user_id
     *
     * @param userId the value for t_user_permission.user_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_permission.permission_id
     *
     * @return the value of t_user_permission.permission_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_permission.permission_id
     *
     * @param permissionId the value for t_user_permission.permission_id
     *
     * @mbggenerated Fri Apr 29 16:48:01 CST 2016
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}